.PHONY: clean All

All:
	@echo "----------Building project:[ Project - Debug ]----------"
	@cd "01_installation_setup" && "$(MAKE)" -f  "Project.mk"
clean:
	@echo "----------Cleaning project:[ Project - Debug ]----------"
	@cd "01_installation_setup" && "$(MAKE)" -f  "Project.mk" clean
