.PHONY: clean All

All:
	@echo "----------Building project:[ 01_challenge - Debug ]----------"
	@cd "02_arrays_vectors" && "$(MAKE)" -f  "01_challenge.mk"
clean:
	@echo "----------Cleaning project:[ 01_challenge - Debug ]----------"
	@cd "02_arrays_vectors" && "$(MAKE)" -f  "01_challenge.mk" clean
