.PHONY: clean All

All:
	@echo "----------Building project:[ 10_exchange_conversion_project - Debug ]----------"
	@cd "10_exchange_conversion_project" && "$(MAKE)" -f  "10_exchange_conversion_project.mk"
clean:
	@echo "----------Cleaning project:[ 10_exchange_conversion_project - Debug ]----------"
	@cd "10_exchange_conversion_project" && "$(MAKE)" -f  "10_exchange_conversion_project.mk" clean
