.PHONY: clean All

All:
	@echo "----------Building project:[ 03_variables_constants - Debug ]----------"
	@cd "03_variables_constants" && "$(MAKE)" -f  "03_variables_constants.mk"
clean:
	@echo "----------Cleaning project:[ 03_variables_constants - Debug ]----------"
	@cd "03_variables_constants" && "$(MAKE)" -f  "03_variables_constants.mk" clean
