.PHONY: clean All

All:
	@echo "----------Building project:[ 01_declaring_initializing_variables - Debug ]----------"
	@cd "03_variables_constants" && "$(MAKE)" -f  "01_declaring_initializing_variables.mk"
clean:
	@echo "----------Cleaning project:[ 01_declaring_initializing_variables - Debug ]----------"
	@cd "03_variables_constants" && "$(MAKE)" -f  "01_declaring_initializing_variables.mk" clean
